# Generated by Django 3.2 on 2023-04-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
